application: metal-air-92115
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
- name: pycrypto
  version: 2.6


handlers:
- url: /static
  static_dir: static
  expiration: "0d 1s"

- url: /assets
  static_dir: assets

- url: /.*
  script: tc.application

skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
